### ISSUE TITLE
Transfer CI to Github Actions

### ISSUE THREAD

**Issue by smcca-oxts** [OxfordTechnicalSolutions/gad-sdk#1]
CI was set up in GitLab so needs to be moved across to work on this platform instead.

This includes:
- CMake build (Windows + Ubuntu 20.04)
- Docs building (and readthedocs page - GitHub Pages?)
- Python Wheels (optional, this would actually be new)

**Comment by slogan-oxts** [comment]
CMake and Docs done, python wheel files action currently disabled.

**Comment by smcca-oxts** [comment]
This is now operational.
