### ISSUE TITLE
Maybe align python "my_first_gad.py" to match C++ version

### ISSUE THREAD

**Issue by s7711** [OxfordTechnicalSolutions/gad-sdk#3]
I think it might be clearer to align the python "my_first_gad.py" example so that it is the same as the C++ version. This will allow users to send real generic aiding updates using python (currently it is set to simulate updates using a CSV file output, I think).

**Comment by smcca-oxts** [comment]
Sensible suggestion - as of v2.0.0 the my_first_gad example has been aligned between python and C++.
